// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// Copier is an autogenerated mock type for the Copier type
type Copier struct {
	mock.Mock
}

// Copy provides a mock function with given fields:
func (_m *Copier) Copy() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
