// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

// Printf provides a mock function with given fields: format, msg
func (_m *Logger) Printf(format string, msg ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, msg...)
	_m.Called(_ca...)
}
